language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: aNPWUw+mHP36Q61mQwxiD4evQJT/qJbQN3oUq3bbR+yPsrLWfcPXYl2ut7YDQ6uljjURrQC2/5e4F+O2dM2JrYuqv3u7XigPv65P/QE7txIA0QIyV52ApGHucf0odryZ1vi8oPjIGym0rqCm/dkK/p2pq2qwSt5gh52iy4kSBYcLObZZHjP9C9i2nU4PSzoFalrqpUvzs4yjJaTZg9/zjY8eMIz0gl8/7rq+eIb4U9By5myCA0mo3TvEkCaHVbj8wV+JqJGv9iuLgIO+cRkgslpiD1jfg5UbpQ1BSlzv8suzDU7Gh5mpsK4bnwHxlta3DY4KMbRCnAq6pTGDi/0pB1iIfT1arl6HWmEqi8/pkEimlRs2jqkk3hftFuPDQDdQFMvaJ334wMPpDb99s+JbaopM8HI31/H9yFDCvZHqRiEC6mG/+NmvrdGg5xyviHBEgTLkTMqLpo73HK+RvcEDzLSXReMRGyHE7Iduz1GFAVj7nA5yX8ZB3ZqkG7H0rWtCBLZ31UyEc4T323DV3ISnxc39UNzrfcIAS1Xo7WgABm2vxp2QOGZ9z/N8UZEsSmE5xeurVsy6lxu11dO369dQrw32x9zZ1EBH9PEiumy0uTwoOuetCb5vpWr2uZSbymkcBrh+Itst8lmrNh7LUS24tyeBf2C4YbAH6cxH9es+QTc=
